---
- set_fact: kickstart_url="{{ zygote_store.http_baseurl }}/{{ prov_dir }}/boot/preseed"

# Build provdir from skel files for the selected pack
- name: Copy skel files
  copy: src="{{ item }}" dest="{{ store_prov_dir }}/boot" remote_src=yes
  with_fileglob:
    - "{{ imageconfig.store_skel_dir }}/*"

- name: Make a temporary directory for prov dir
  become: no
  local_action: tempfile state=directory
  register: local_prov_dir

- shell: "find {{ imageconfig.store_skel_dir }} -type f"
  register: files_to_copy

- fetch: src="{{ item }}" dest="{{ local_prov_dir.path }}/"
  with_items: "{{ files_to_copy.stdout_lines }}"

- name: Build pxelinux.cfg
  template:
    src: "{{ local_prov_dir.path }}/{{ inventory_hostname }}/{{ imageconfig.store_skel_dir }}/boot/pxelinux.cfg.j2"
    dest: "{{ store_prov_dir }}/boot/pxelinux.cfg"

- name: Build preseed
  template: src=preseed.j2 dest="{{ store_prov_dir }}/boot/preseed"

- name: Build late_command
  template: src=late_command.j2 dest="{{ store_prov_dir }}/boot/late_command"

- name: Build dnsmasq boot options config
  template: src=prov-bootoptions.conf.j2 dest="{{ zygote_config.config_root }}/dnsmasq-{{ zygote_network.interface }}.conf.d/70-provisioned-images.conf.d/boot-{{ prov_id }}.conf"

- name: Restart dnsmasq services
  command: "sudo systemctl restart dnsmasq@{{ zygote_network.interface}}.service"
