---
- package:
    state: present
    name:
      - nginx
      - fcgiwrap

- include_role: name=nginx tasks_from=gentoo
  when: ansible_os_family == "Gentoo"

- name: Disable default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx
