---
- package: state=present name=nginx
- service: name='nginx' enabled=yes state=started
    
- include_role: name=nginx tasks_from=gentoo
  when: ansible_os_family == "Gentoo"

- file: path=/etc/nginx/sites-enabled/default state=absent
  notify:
    - reload nginx

