---
- hosts: all

  roles:
    - gaqzi.ssh-config

  tasks:
    - name: Create the key used by vagrant
      delegate_to: localhost
      ssh_config:
        user: "{{ lookup('env', 'USER') }}"
        host: "{{ inventory_hostname }}"
        hostname: "{{ ansible_host }}"
        identity_file: "{{ ansible_ssh_private_key_file }}"
        port: "{{ ansible_port }}"
        remote_user: "{{ ansible_user }}"
        state: present
