---
- hosts: vmwares

  vars:
    provision: false

  # For provisioning only, gathering facts doesn't work until the host is provisioned
  gather_facts: False

  roles:
    - zygote_config
    - { role: provision-esxi, delegate_to: "{{ origin_zygote }}", ansible_user: "{{ zygote_config.user }}", when: 'provision | bool' }

- hosts: vmwares

  vars:
    provision: False

  roles:
    # This role is not 100% idempotent
    - { role: esxi-datastores, when: provision }
    # Don't have proper certificate generation yet
    - esxi-networking


