---
- hosts: vmwares

  vars:
    provision: false

  # For provisioning only, gathering facts doesn't work until the host is provisioned
  gather_facts: False

  roles:
    - { role: provision-esxi, delegate_to: "{{ origin_zygote }}", ansible_user: "{{ hostvars[origin_zygote].zygote_config.user }}", when: provision }

- hosts: vmwares

  roles:
    - esxi-datastores
    - esxi-directories
    - esxi-scratchspace
    - esxi-networking
    - ovftool
