---
- hosts: zygotes

  # This part needs to be run as root
  become: yes

  roles:
    - zygote

- hosts: zygotes

  become: yes

  # This is where images are deployed

  roles:
    - tags: images
      role: systemrescuecd-image
      iso_path: "systemrescuecd-x86-4.9.0.iso"
      srm_modules:
        - zfs-core-4.4.28-std490-amd64.srm
        - zfs-kmod-4.4.28-std490-amd64.srm

    - tags: images
      role: systemrescuecd-image
      image_name: systemrescuecd-x86-default
      iso_path: "systemrescuecd-x86-4.9.6.iso"

    - tags: images
      role: debian-netboot-image
      image_name: debian-x86-default
      repo_baseurl: http://http.us.debian.org/debian/dists/stable/

    - tags: default-images
      role: provision-default
      image_name: systemrescuecd-x86-default
      provision_role: provision-surveyship

      # This is a well-known provisioning name, not a single-shot one
      prov_id: default-x86

