---
- name: Create user for running zygote
  user:
    name: "{{ zygote_config.user }}"
    groups: "{{ ssh_access_group }}"

- name: Add SSH keys for "{{ zygote_config.user }}"
  authorized_key:
    key: "{{ item.type }} {{ item.key }} {{ item.name }}"
    user: "{{ zygote_config.user }}"
  with_items: "{{ admin_ssh_keys }}"

- name: Install packages
  package:
    state: present
    name:
      - sudo
      - pwgen
      - dnsmasq

- name: Create the directories (root owned)
  file: path="{{ item }}" state=directory 
  with_items:
    - "{{ zygote_store.tftproot }}"
    - "{{ zygote_store.tftproot }}/cgi-bin"
    - "{{ zygote_config.config_root }}"

- name: Create directories available to "{{ zygote_config.user }}"
  file: path="{{ item }}" state=directory owner="{{ zygote_config.user }}"
  with_items:
    - "{{ zygote_store.tftproot }}/host"
    - "{{ zygote_store.tftproot }}/images"
    - "{{ zygote_config.config_root }}/hosts-{{ zygote_network.interface }}.d"
    - "{{ zygote_config.config_root}}/dnsmasq-{{ zygote_network.interface }}.conf.d"

- name: Get the IPv4 address of the interface where the nodes are
  set_fact: nginx_ipv4_address="{{ hostvars[inventory_hostname]['ansible_' + zygote_network.interface].ipv4.address }}"

- name: Calculate begin of allowed IPv4 DHCP server range
  set_fact: dhcp_server_ipv4_range_begin="{{ ((nginx_ipv4_address | ipaddr('int') | int) + 1) | ipaddr('ipv4') | ipaddr('address') }}"

- name: Calculate end of allowed IPv4 DHCP server range
  set_fact: dhcp_server_ipv4_range_end="{{ ((hostvars[inventory_hostname]['ansible_' + zygote_network.interface].ipv4.broadcast | ipaddr('int') | int) - 1) | ipaddr('ipv4') | ipaddr('address') }}"

- name: Install files from templates
  template: src="{{ item.src }}" dest="{{ item.dest if item.dest is defined else (item.destdir + '/' + (item.src | basename | replace('.j2',''))) }}"
  with_items:
    - src: dnsmasq@.service.j2
      destdir: "{{ zygote_config.systemd_unit_root }}"
    - src: fcgiwrap-zygote.socket.j2
      destdir: "{{ zygote_config.systemd_unit_root }}"
    - src: fcgiwrap-zygote.service.j2
      destdir: "{{ zygote_config.systemd_unit_root }}"
    - src: zygote_site.conf.j2
      destdir: "/etc/nginx/sites-available"
    - src: allow-dnsmasq-restart.j2
      destdir: /etc/sudoers.d
    - src: dnsmasq.conf.j2
      dest: "{{ zygote_config.config_root }}/dnsmasq-{{ zygote_network.interface }}.conf"
    - src: host-index.html
      dest: "{{ zygote_store.tftproot }}/host/index.html"
    - src: report-state.cgi.j2
      destdir: "{{ zygote_store.tftproot }}/cgi-bin"

- name: Make report-state CGI executable
  file: path="{{ zygote_store.tftproot }}/cgi-bin/report-state.cgi" state=file mode="0755"

- name: Enable nginx site
  file: path=/etc/nginx/sites-enabled/zygote_site.conf src=/etc/nginx/sites-available/zygote_site.conf state=link

- name: Enable IPv4 forwarding
  sysctl: name=net.ipv4.ip_forward value=1 state=present
  when: "{{ zygote_network.ipv4_forwarding | default(false) }} == true"

# This is needed because the default dnsmasq on debian listens on *:53 preventing us from starting
- name: Disable builtin dnsmasq
  service: name='dnsmasq.service' enabled=no state=stopped
  when: ansible_os_family == "Debian"

- name: Start dnsmasq
  service: name='dnsmasq@{{ zygote_network.interface }}.service' enabled=yes state=restarted

- name: Make sure nginx is restarted and enabled
  service: name=nginx enabled=yes state=restarted

- name: Make sure fcgiwrap is restarted and enabled
  service: name=fcgiwrap-zygote.socket enabled=yes state=started

##
## Store zygote configuration as local facts
##

- name: Create local facts directory
  file: state=directory recurse=yes path=/etc/ansible/facts.d

- name: Install local facts from templates
  template: src="{{ item }}" dest="/etc/ansible/facts.d/{{ item | basename | replace('.j2','') }}"
  with_items:
    - zygote_config.fact.j2
    - zygote_store.fact.j2
    - zygote_network.fact.j2
    - zygote_images.fact.j2

- name: Make image enumerator fact executable
  file: path=/etc/ansible/facts.d/zygote_images.fact state=file mode=0755

