---
- name: Make a boot ID
  command: "pwgen -s -1 16"
  run_once: True
  register: prov_id

- name: Get origin zygote vars
  set_fact:
    zygote_store="{{ hostvars[origin_zygote].zygote_store }}"
    zygote_network="{{ hostvars[origin_zygote].zygote_network }}"

- name: Load image descriptor
  include_vars:
    name: imageconfig
    file: "{{ zygote_store.tftproot }}/{{ esxi_image_path }}/imageconfig.yml"

- name: Hack, dont know why the imageconfig gets created in hostvars[origin_zygote]
  set_fact: imageconfig="{{ hostvars[origin_zygote].imageconfig }}"

- name: Set prov directories
  set_fact:
    prov_dir: "host/{{ prov_id.stdout }}"
    store_prov_dir: "{{ zygote_store.tftproot }}/host/{{ prov_id.stdout }}"

- name: Build a kickstart URL for this prov
  set_fact: kickstart_url="{{ zygote_store.http_baseurl }}/{{ prov_dir }}/boot/ks.cfg"

- name: Create layout for prov "{{ prov_dir }}"
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ store_prov_dir }}"
    - "{{ store_prov_dir }}/boot"
    - "{{ store_prov_dir }}/state"

- name: Add permissions to allow access by state-report.cgi
  acl: path="{{ store_prov_dir }}/state" etype=user entity="{{ zygote_store.cgi_bin_user }}" permissions=rwx state=present

# Build provdir from skel files for the selected pack
- name: Copy skel files
  copy: src="{{ item }}" dest="{{ store_prov_dir }}/boot"
  with_fileglob:
    - "{{ imageconfig.store_skel_dir }}/*"

# Customize the pack
- name: Build the kickstart file
  template: src=./ks.cfg.j2 dest="{{ store_prov_dir }}/boot/ks.cfg"

- name: Build boot.cfg
  template:
    src: "{{ store_prov_dir }}/boot/boot.cfg.j2"
    dest: "{{ store_prov_dir }}/boot/boot.cfg"
    
- name: Create dhcp options for prov
  template: src="prov-bootoptions.conf.j2" dest="{{ zygote_config.config_root }}/dnsmasq-{{ zygote_network.interface }}.conf.d/boot-{{ prov_id.stdout }}-options.conf"

- name: Direct host being provisioned to boot specified prov tag
  template: src="prov-hostoptions.conf.j2" dest="{{ zygote_config.config_root }}/hosts-{{ zygote_network.interface }}.d/host-{{ ansible_host }}.conf"

- name: Restart dnsmasq services
  command: "sudo systemctl restart dnsmasq@{{ zygote_network.interface}}.service"

# Here is where the machine should be booted up!!!
# This is a manual step
- name: Prompt for boot
  pause: prompt="Boot {{ ansible_host }} and press Enter to continue"

- name: Wait until the installer ends
  wait_for: path="{{ store_prov_dir }}/state/post-install" state=present delay=30 timeout=600

# Installer has finished
- name: Cleanup prov "{{ prov_id.stdout }}"
  file:
    state: absent
    path:
      - "{{ zygote_config.config_root }}/dnsmasq-{{ zygote_network.interface }}.conf.d/boot-{{ prov_id.stdout }}-options.conf"
      - "{{ zygote_config.config_root }}/hosts-{{ zygote_network.interface }}.d/host-{{ ansible_host }}.conf"
      - "{{ store_prov_dir }}"

- name: Restart dnsmasq services
  command: "sudo systemctl restart dnsmasq@{{ zygote_network.interface}}.service"

- name: Wait for SSH
  wait_for_connection: delay=30 timeout=600

- name: Fetch the SSH server key
  delegate_to: localhost
  command: "ssh-keyscan {{ ansible_host }}"
  register: ssh_key

- name: Remember SSH key
  delegate_to: localhost
  known_hosts: name="{{ ansible_host }}" key="{{ ssh_key.stdout }}"

- name: Collect facts
  setup:
