---
- set_fact: vm_dir="/vmfs/volumes/{{ esxi_config.vm.datastore }}/{{ esxi_config.vm.name }}"
- set_fact: vmx_path="/vmfs/volumes/{{ esxi_config.vm.datastore }}/{{ esxi_config.vm.name }}/{{ esxi_config.vm.name }}.vmx"

- set_fact: iso="{{ hostvars[esxi_config.host].iso_store }}/{{ esxi_config.vm.iso }}"
  when: esxi_config.vm.iso is defined

- name: Create directory for the VM
  file: state=directory path="{{ vm_dir }}"

- name: Check if not yet registered
  shell: "vim-cmd vmsvc/getallvms | grep -F '{{ esxi_config.vm.display_name }}' | awk '{print $1;}'"
  register: vmlist_out

- name: Create VMX file for the VM
  template: src="basic.vmx.j2" dest="{{ vmx_path }}"
  vars:
    vm: "{{ esxi_config.vm }}"
  when: vmlist_out.stdout == "" 

- name: Create VMDK disks
  command: "vmkfstools -c {{ item.size_gb }}G {{ vm_dir }}/{{ item.name }}.vmdk"
  args:
    creates: "{{ vm_dir }}/{{ item.name }}.vmdk"
  with_items: "{{ esxi_config.vm.disks }}"

- name: Register VMX
  command: "vim-cmd solo/registervm {{ vmx_path }}"
  when: vmlist_out.stdout == ""

- name: Find virtual machine ID
  delegate_to: "{{ esxi_config.host }}"
  shell: "vim-cmd vmsvc/getallvms | grep -F '{{ esxi_config.vm.display_name }}' | awk '{print $1;}'"
  register: vmlist_out

- name: Get VM state
  delegate_to: "{{ esxi_config.host }}"
  shell: "grep 'generatedAddress = ' {{ vmx_path }} || true"
  register: vmaddr_out

#
# We need to powerup/powerdown to generate the MAC addresses
#
- name: Power on virtual machine
  delegate_to: "{{ esxi_config.host }}"
  command: "vim-cmd vmsvc/power.on {{ vmlist_out.stdout }}"
  when: vmaddr_out.stdout == ''

- name: Power off virtual machine
  delegate_to: "{{ esxi_config.host }}"
  command: "vim-cmd vmsvc/power.off {{ vmlist_out.stdout }}"
  when: vmaddr_out.stdout == ''


