---
- name: Gather facts from origin zygote
  delegate_to: "{{ origin_zygote }}"
  setup:

- name: Load common provisioning tasks
  include_role: name=provision-common tasks_from=create.yml

- name: Load image provisioning role
  import_role: name="{{ provision_role }}"

- name: Build dnsmasq host file
  template: src=prov-hostoptions.conf.j2 dest="{{ zygote_config.config_root }}/dnsmasq-eth1.conf.d/30-hosts.conf.d/host-{{ inventory_hostname }}.conf"

- name: Restart dnsmasq services
  command: "sudo systemctl restart dnsmasq@{{ zygote_network.interface}}.service"

# Power on hardware
- include: "{{ power_ctrl_task }}"

- name: Execute common cleanup tasks
  include_role: name=provision-common tasks_from=wait.yml
  vars:
    state: boot-complete
    
- name: Execute common cleanup tasks
  include_role: name=provision-common tasks_from=cleanup.yml

