---
- include_role:
    name: esxi-datastore
  with_items:
    - "{{ esxi_config.storage.datastores }}"
  loop_control:
    loop_var: datastore

- include_role:
    name: esxi-passthrough
  with_items:
    - "{{ esxi_config.storage.passthrough }}"
  loop_control:
    loop_var: passthrough

- name: Download images to local disk
  delegate_to: localhost
  command: "wget --no-clobber -O {{ item.local_file }} {{ item.url }}"
  args:
    creates: "{{ item.local_file }}"
  with_items: "{{ images }}"

