---
zygote_config:
  user: zygote
  groups:
    - ssh-user
  config_root: /etc/zygote
  systemd_unit_root: /etc/systemd/system

zygote_network:
  interface: node-network

zygote_store:
  tftproot: /tftproot

