---

- name: Get out zygote information from ansible_local
  set_fact:
    zygote_config="{{ ansible_local.zygote_config }}"
    zygote_store="{{ ansible_local.zygote_store }}"
    zygote_network="{{ ansible_local.zygote_network }}"

- name: Install required packages
  package:
    state: present
    name:
      - p7zip-full

# For some of these vars look into vars/main.yml
- name: Create dirs for image
  file: path="{{ item }}" state=directory
  with_items:
    - "{{ store_tgt_dir }}"
    - "{{ store_skel_dir }}"

- name: Stat the ISO file
  stat: path="{{ store_tgt_dir }}/{{ iso_path | basename }}"
  register: iso_stat_data

- name: Copy ISO
  copy: src="{{ iso_path }}" dest="{{ store_tgt_dir }}"
  when: iso_stat_data.stat.exists == false

- name: Extract ISO to image directory
  # iso_extract:
  #   image: "{{ zygote_config.tftproot }}/{{ vmware.software_tag }}/{{ vmware.version_tag }}/{{ vmware.iso_file | basename }}"
  #   dest: "{{ zygote_config.tftproot }}/{{ vmware.software_tag }}/{{ vmware.version_tag }}"
  #   files: "*"
  # Travel without moving ...
  command: "7z x -o{{ store_tgt_dir }} {{ store_tgt_dir }}/{{ iso_path | basename }}"
  args:
    creates: "{{ store_tgt_dir }}/sysrcd.dat"

- name: Copy in SRM modules
  copy: src="{{ item }}" dest="{{ store_tgt_dir }}"
  with_items: "{{ srm_modules }}"
  when: srm_modules is defined

- name: Stat SRM modules
  stat: path="{{ store_tgt_dir }}/{{ item }}"
  with_items: "{{ srm_modules }}"
  register: srm_stat_data
  when: srm_modules is defined

- debug: var=srm_stat_data

- name: Generate SRM checksum files
  copy: dest="{{ store_tgt_dir }}/{{ item.item | splitext | first }}.md5" content="{{ item.stat.md5 }} {{ item.item }}"
  with_items: "{{ srm_stat_data.results }}"
  when: srm_stat_data.results is defined

- name: Enable dnsmasq to read from the image dirs
  acl: path="{{ store_tgt_dir }}" recursive=yes etype=user entity={{ zygote_config.dnsmasq_user }} permissions=rx state=present

- name: Build image desriptor
  set_fact:
    imgconfig:
      image_name: "{{ image_name }}"
      tgt_dir: "{{ tgt_dir }}"
      store_tgt_dir: "{{ zygote_store.tftproot }}/{{ tgt_dir }}"
      skel_dir: "{{ tgt_dir }}/skel"
      store_skel_dir: "{{ zygote_store.tftproot }}/{{ skel_dir }}"
      http_baseurl: "{{ zygote_store.http_baseurl }}"
      provision_role: "{{ provision_role }}"

- name: Dump configuration for this image
  copy: dest="{{ store_tgt_dir }}/imageconfig.json" content="{{ imgconfig | to_json }}"

- name: Reload facts to read the ansible_local
  setup:
