---
origin_zygote: shoggoth

netboot_image_path: images/debian-jessie-netboot

esxi_config:

  host: newton

  vm:
    auth:
      users:
        - userid: root
          password_hash: "{{ admin_root_password | password_hash('sha512') }}"
          authorized_keys: "{{ admin_ssh_keys }}"
          ssh_dir: /root/.ssh/

    name: debiantest
    display_name: debiantest

    datastore: datastore1
    vcpus: 1
    ramsize_mb: 2048
    disks:
      - name: state
        size_gb: 16

    ifaces:
      - name: lan
        plug_into: VM Network
      - name: sublan
        plug_into: VMs

    # This should be the name of the network from the hash above where a zygote is connected
    prov_network: VM Network

zygote_network:
  interface: eth1

  # Setup IPv4 forwarding, needed when this zygote will be a router for other zygotes
  ipv4_forwarding: true

zygote_store:
  tftproot: /tftproot
