---
tgt_dir: "images/{{ esxi_iso_path | basename | replace('.iso','') }}"
store_tgt_dir: "{{ zygote_store.tftproot }}/{{ tgt_dir }}"
skel_dir: "{{ tgt_dir }}/skel"
store_skel_dir: "{{ zygote_store.tftproot }}/{{ skel_dir }}"

# This is Gentoo-specific
syslinux_gpxelinux_image: /usr/share/syslinux/gpxelinux.0
